### PR TITLE
Nitpicking at the usage printout

### PR DESCRIPTION
**Pull request by maxim-levy**
An extra \n removed to make the printout look uniform

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
Thanks! Please fill the form from https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes and we'll get this merged.

**Comment by maxim-levy** [comment]
just did

**Comment by MonsieurNicolas** [comment]
Thanks!

**Comment by MonsieurNicolas** [comment]
r+ ad385c53349d872698ab8691e263923b82d741d8

**Comment by MonsieurNicolas** [comment]
@latobarita: retry

**Pull request merged**
