### PR TITLE
Do not clear tx queue for good accounts

### PR DESCRIPTION
**Pull request by MonsieurNicolas**
This PR fixes an issue introduced in #2158 where the transaction queue for an account was reset entirely when removing transactions that were processed by the network

### CODE REVIEW

**Comment by jonjove** [comment]
r+ 7d13aae

**Comment by MonsieurNicolas** [comment]
@latobarita: retry

**Comment by MonsieurNicolas** [comment]
@latobarita: retry

**Comment by MonsieurNicolas** [comment]
@latobarita: retry

**Comment by MonsieurNicolas** [comment]
r+ 93bb58a366a48e94716a3413f124e952b1440f3e

**Pull request merged**
