### PR TITLE
fix typo in admin.m

### PR DESCRIPTION
**Pull request by nicokunz**
The word "to" is missing from the sentence. I had included a suggested replacement for the whole paragraph below.

It would be better to change the two sentences from:
Here, each player can decide to look wherever they want. Even look at only one
other player, which is a risk if this other player decides to quit the game.

To:
Here each player can decide to look wherever they want, even if they can only see one other player (or nobody). This is risky if that player quits the game or is not following the rules.

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
yeah I agree, you can make the change.
Note that in order to open a pull request you need to sign the form, see https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes

**Comment by nicokunz** [comment]
I have signed the agreement and updated the text.

**Comment by MonsieurNicolas** [comment]
cool thank you. please squash the commits so that we can merge it as one change

**Comment by MonsieurNicolas** [comment]
this section of the doc was removed in the new version of the admin guide

**Pull request closed without merging**
