### PR TITLE
Reduce trustline limits after fuzzer offer setup

### PR DESCRIPTION
**Pull request by rokopt**
# Reduce trustline limits after fuzzer offer setup

Part of #1376 

As a follow-on to PR #2858 , which reduced account balances after setting up offers for fuzzing, reduce trust line limits similarly.  The idea is to make it plausible that the fuzzer will sometimes attempt operations which would exceed limits.

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v5.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [ ] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

**Comment by jonjove** [comment]
You mean "limit" in both the PR and the commit, right?

**Comment by rokopt** [comment]
> You mean "limit" in both the PR and the commit, right?

Oops, yes, thanks!  At least I wrote "limits" in the code....  I've rebased to change the log message, and edited the PR.

**Comment by MonsieurNicolas** [comment]
Same thing than #2891 - we might be better off flipping the setup on its head, and enumerate what we want directly. It's becoming very hard to understand what the end result is for each account + order book

**Comment by rokopt** [comment]
> Same thing than #2891 - we might be better off flipping the setup on its head, and enumerate what we want directly. It's becoming very hard to understand what the end result is for each account + order book

See my reply to the same comment on #2891 : https://github.com/stellar/stellar-core/pull/2891#issuecomment-768669956

**Comment by rokopt** [comment]
Now that PR #2897 has been merged, this should be done in the same style as that PR.  I've done that in PR #2927 , so this one is superseded.

**Pull request closed without merging**
