### PR TITLE
fix: fix the enum-body format in XDR.

### LINKED ISSUE #2954: XDR format is not standardized (Version: The latest source code)
## Issue Description

According to the contents of [RFC-4506](https://tools.ietf.org/html/rfc4506), the format of the enum-body should be
```
enum-body:
         "{"
            ( identifier "=" value )
            ( "," identifier "=" value )*
         "}"
```
However, the XDR definition in the [source code](https://github.com/stellar/stellar-core/blob/2f43c6231e/src/xdr/Stellar-transaction.x#L51) does not meet the above requirements, which may cause some XDR parsers to fail to parse this code normally.

## Expected Result
Follow the RFC-4506 specification.

### PR DESCRIPTION
**Pull request by overcat**
# Description

Resolves #2954

According to the contents of [RFC-4506](https://tools.ietf.org/html/rfc4506), the format of the enum-body should be
```
enum-body:
         "{"
            ( identifier "=" value )
            ( "," identifier "=" value )*
         "}"
```
However, the XDR definition in the [source code](https://github.com/stellar/stellar-core/blob/2f43c6231e/src/xdr/Stellar-transaction.x#L51) does not meet the above requirements, which may cause some XDR parsers to fail to parse this code normally.

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v8.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [x] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
Thanks @overcat .

This PR is valid so I am re-opening it and merging. The xdr compiler that we use should have caught this.

**Comment by MonsieurNicolas** [comment]
r+ 094ad2869f3c694275c18d8631018963c4f483a2

**Comment by MonsieurNicolas** [comment]
ooops didn't see that we have an existing PR fixing this already

**Comment by jonjove** [comment]
I'm going to reopen and merge this because we are still finalizing the other PR that was going to fix it.

**Comment by jonjove** [comment]
r+ 094ad28

**Comment by stanford-scs** [comment]
I have fixed this by adding a `-pedantic` flag for cases where strict adherence to RFC4506 is desired.

**Comment by stanford-scs** [comment]
Sorry, I closed the issue on the wrong repo.  The pedantic flag has been added upstream to xdrpp, but not yet merged into stellar-core.

**Pull request merged**
