### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by alfiedotwtf**
fix typo

Note: I have signed the contributor's license.

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
Thanks for the PR.
can you fill the form from https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes and we'll get this merged

**Comment by alfiedotwtf** [comment]
Hey @MonsieurNicolas, yep already signed it :)

**Comment by alfiedotwtf** [comment]
Sneaking in one more commit to this PR

**Comment by MonsieurNicolas** [comment]
Thanks (sorry I missed that you already signed it).
LGTM

**Comment by alfiedotwtf** [comment]
Awesome. Thank you!

**Pull request merged**
