### PR TITLE
Fix Travis ccache integration

### PR DESCRIPTION
**Pull request by MonsieurNicolas**
Looks like Travis run don't cache enough (lots of cache misses).

Logs show that `tar` is failing, pointing to a misconfiguration.

This PR switches to using the "built-in" ccache defaults.

### CODE REVIEW

**Comment by graydon** [comment]
r+ aa7f65a

**Comment by MonsieurNicolas** [comment]
@latobarita: retry

**Comment by MonsieurNicolas** [comment]
r+ 0e59be7a7a15b42fc767b569716d633f18c7b898

**Comment by MonsieurNicolas** [comment]
r+ 75d8699b715edf3551099c377d806c84bef7a975

**Comment by MonsieurNicolas** [comment]
r+ 6471196f18ff0578c674af91149a166cd3e4bd20

**Pull request merged**
