### PR TITLE
Update docs/db-schema.md

### PR DESCRIPTION
**Pull request by Arkweid**
# Description

Update `docs/db-schema.md`
- Fixed broken links to file definition;
- altered field `type` for `peers`;
- `PRIMARY KEY` added for: `upgradehistory`, `peers`, `quoruminfo`, `scpquorums`, `txfeehistory`, `txhistory`, `accountdata`, `trustlines`, `offers`;
- `ban`, `publishqueue`, `pubsub` tables added.

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
you're probably not working off master: those schema changes look like reverts from changes made a while back

**Comment by Arkweid** [comment]
Could you explain a little more detailed?

**Comment by MonsieurNicolas** [comment]
there is no "signers" table anymore for example

**Comment by Arkweid** [comment]
I thought we would create it here, along with the "accounts" table:
https://github.com/stellar/stellar-core/blob/master/src/ledger/LedgerTxnAccountSQL.cpp#L543-L551

**Comment by MonsieurNicolas** [comment]
This is a side effect of old schemas, the latest schema doesn't have that. See https://github.com/stellar/stellar-core/blob/master/src/database/Database.cpp#L212 ; I opened issue https://github.com/stellar/stellar-core/issues/2200 as it's confusing to have upgrade code scattered in the code base like this

Thanks

**Comment by Arkweid** [comment]
@MonsieurNicolas got it. I updated this PR and description. Could you review it again?

**Pull request merged**
