### PR TITLE
Add the packaging metadata to build the stellar-core snap

### PR DESCRIPTION
**Pull request by elopio**
This package will let you publish the latest stellar-core in the Ubuntu store, and from there reach many users on all the supported Ubuntu versions, and more Linux distributions in progress. You just have to go to https://build.snapcraft.io and enable the automated continuous delivery.

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
Thanks.
I would rather have only stable releases go through this and not the latest master. From the looks of it, it seems this should live in a place where we already track stable releases like in https://github.com/stellar/docker-stellar-core or make a separate repo ?

**Comment by elopio** [comment]
Hello @MonsieurNicolas! Thanks for the review.

You can move it to a separate repo, and use `source: https://github.com/stellar/stellar-core.git` and `source-tag` to only update it when there's a new stable release.

I personally prefer to have the latest code always available in the edge channel of the store, where it can be used by your early adopters and the ubuntu community of testers to find bugs before you release to stable. I wrote a little about this here: http://elopio.net/blog/ipfs-crowdtesting/

But, the big goal of snapcraft is to be flexible enough to not be a burden for your release process. Feel free to adjust it to your preference. I'm available if you have questions or would like suggestions about releasing and crowdtesting on Linux. Just ping me.

pura vida.

**Comment by elopio** [comment]
Ping, any chance we could get stellar in the store soon? :)

**Comment by MonsieurNicolas** [comment]
Ah yes, I think https://github.com/stellar/packages was created more recently, and it's a better home for this as we can follow the same release process than debian packages (tracking master is not useful) - and this probably has the same subtleties (setting up a node is not just running the binaries).

**Comment by elopio** [comment]
@MonsieurNicolas it sounds good, if that's your preference. 
I'm very excited today looking at the recent [parity release to the stable channel in the store](https://github.com/paritytech/parity#install-from-the-snap-store) and would love to see more decentralization in there. Let me know if I can help you to make it happen.

**Comment by MonsieurNicolas** [comment]
sweeping stale pull requests

**Pull request closed without merging**
