### PR TITLE
fix duplicate lines in usage

### PR DESCRIPTION
**Pull request by stanford-scs**

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
r+ ce2f4f8bfe6eb710f64505cee35cc358b30e198c

**Comment by MonsieurNicolas** [comment]
@latobarita: retry ce2f4f8bfe6eb710f64505cee35cc358b30e198c

**Comment by MonsieurNicolas** [comment]
@latobarita: retry

**Comment by MonsieurNicolas** [comment]
@latobarita: retry ce2f4f8

**Comment by vogel** [comment]
@latobarita: retry

**Pull request merged**
