### PR TITLE
include Stellar-SCP.h in Stellar-ledger.x

### LINKED ISSUE #1208: Stellar-ledger.x should have Stellar-SCP.h include
I believe Stellar-ledger.x should have a Stellar-SCP.h include added.

I'm including the Stellar-ledger.h generated from xdrc in my own project, and am getting errors like `SCPEnvelope was not declared in this scope`.

### PR DESCRIPTION
**Pull request by vogel**
Fixes #1208

Signed-off-by: Rafał Malinowski <rafal.przemyslaw.malinowski@gmail.com>

### CODE REVIEW

**Comment by stanford-scs** [comment]
This seems like a bit of an abstraction violation.  What is the dependence between transactions and the consensus protocol?  If there's some data structure used by both, then ideally it should go in Stellar-types.x (or we should get rid of Stellar-types.x and merge it into Stellar-SCP).

**Comment by vogel** [comment]
Second version uploaded.
Some struct from Stellar-ledger.x are now moved into Stellar-SCP.x.
Stellar-overlay.x now includes Stellar-SCP.h (as StellarMessage require SCPQuorumSet and SCPEnvelope).

What do you think?

**Comment by MonsieurNicolas** [comment]
The SCP library should stay more or less agnostic of how it is used. Right now it happens to live in the stellar-core code base but it should be trivial for somebody to just take it.
This change seems to add application specific dependencies into the SCP world, which is wrong.
I don't know what the previous iteration of this PR looked like, but Stellar-ledger.x should probably include Stellar-SCP.h as it defines the XDR structures used in the history subsystem (we may want to create a dedicated file for it at some point).

**Comment by vogel** [comment]
Restored & rebased previous version of this PR - Stellar-ledger.x includes Stellar-SCP.h

**Comment by MonsieurNicolas** [comment]
r+ 0e2c8598c238f9fa1da71f0093bda440197a40e4

**Pull request merged**
