### PR TITLE
Fixes to HistoryTests and ProcessExitEvent

### PR DESCRIPTION
**Pull request by marta-lokhova**

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
r+ f65aab6d76c54db10530c79c16947db47a695397

**Comment by marta-lokhova** [comment]
looks like one of the new work tests failed, investigating

**Comment by marta-lokhova** [comment]
should be good to go now

**Comment by MonsieurNicolas** [comment]
@latobarita: retry

**Pull request merged**
