### PR TITLE
Remove generated files from build and update gitignore

### LINKED ISSUE #1580: remove generated files from build
For some reason `stellar-core.1.in` is included in git, which causes the tree to be "dirty" if documentation gets updated.

This file should be removed from source control, and properly ignored in `.gitignore` as it will be re-generated anyways.

There might be more files like this.

### PR DESCRIPTION
**Pull request by evanlimanto**
Fixes #1580.

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
r+ 860fb0c530a5611c9c9d04bc5090803e46bc6f40

**Comment by MonsieurNicolas** [comment]
Thanks, like always!

**Comment by evanlimanto** [comment]
hm seems like pandoc is not installed during CI, and so we get this error:
```
pandoc -s -f markdown -t man -o "./docs/stellar-core.1.in~" tmp.man.md \
	    && mv -f "./docs/stellar-core.1.in~" "./docs/stellar-core.1.in"
/bin/bash: pandoc: command not found
make[2]: [docs/stellar-core.1] Error 127 (ignored)
rm -f tmp.man.md
sed -e "s|%prefix%|/usr/local|g" "./docs/stellar-core.1.in" > "docs/stellar-core.1~" \
	    && mv -f "docs/stellar-core.1~" "docs/stellar-core.1"
sed: can't read ./docs/stellar-core.1.in: No such file or directory
```
i tried adding pandoc to .travis.yml, so we'll have to see if that works?

**Comment by MonsieurNicolas** [comment]
yes, let's give this a go. Thanks!

**Comment by MonsieurNicolas** [comment]
r+ 77912c17375103cabf26cd98da1548dd156ce177

**Pull request merged**
