### PR TITLE
Enable tests

### PR DESCRIPTION
**Pull request by sisuresh**

### CODE REVIEW

**Comment by sisuresh** [comment]
r+ 1f1d187ec9fd80ba7935c13048a04e62a69f0dc5

**Comment by MonsieurNicolas** [comment]
r+ 0a8b913d89cd9bc719639754a20011c14151c5e7

**Comment by sisuresh** [comment]
r+ 808349cd444bf3aa020716e2103c2ed0f46fd90e

**Comment by sisuresh** [comment]
r+ 6839e255123248fc16db509bbed7a7a9bac2e71c

**Comment by sisuresh** [comment]
r+ 33ba2a575ed51de0c1a5a01d470cba8dad112b63

**Comment by sisuresh** [comment]
r+ b01477d7f6de330242d80cf1f511c3c2fb564ac2

**Comment by sisuresh** [comment]
r+ 29aaa08d51b2ea041ff821966463bd123f825338

**Comment by sisuresh** [comment]
r+ 86d5b23aa476a74bbd332c0730471092a1ef947b

**Comment by sisuresh** [comment]
r+ fad82cfb2a7088e8b9bed8321b301727af96ec30

**Comment by sisuresh** [comment]
r+ dce581bf4f3ab59c1621a97fc56051283d9fd218

**Comment by sisuresh** [comment]
r+ 21cc8832039f85998311aa33d622b398edbb4af9

**Comment by sisuresh** [comment]
r+ 90b0a2e703ca0b30d2b2cd57ade6f12764453ae1

**Comment by sisuresh** [comment]
r+ c7fb8e2455e2cde8bb68ed18721e70958450cf97

**Comment by sisuresh** [comment]
r+ ba21f039cb90c631d37fba95643292e65e618608

**Comment by sisuresh** [comment]
r+ b3de3d964b194f09406c1af314a31681e272dc59

**Comment by sisuresh** [comment]
r+ ce820157ed60f6c168f98bd960228598235ab0f7

**Pull request closed without merging**
