### PR TITLE
properly apply buffered ledger when catching up

### PR DESCRIPTION
**Pull request by MonsieurNicolas**

### CODE REVIEW

**Comment by sisuresh** [comment]
I'm not sure if this fixes the problem. In `Work.cpp`, we always return `WORK_RUNNING` after `child->crankWork()` is called, even if the child succeeds on that `crankWork`. I think another ledger can come in after this point before the `LedgerManager` is made aware that catchup is done. Does this make sense? @marta-lokhova

**Comment by marta-lokhova** [comment]
I think what @MonsieurNicolas proposes is that if another ledger comes in, we just reset ApplyBufferedLedgersWork and run it again (and do so until the queue is empty), at which point `CatchupWork` can return success, and trigger LedgerManager callback.

**Comment by sisuresh** [comment]
Ah my bad

**Comment by marta-lokhova** [comment]
ok @MonsieurNicolas made a few local edits to repro the issue, i think this change works. This way seems less error-prone, what do you think @sisuresh?

**Comment by sisuresh** [comment]
Yeah this change is much simpler

**Comment by MonsieurNicolas** [comment]
ok, I am r+ this then thanks for the follow up! @sisuresh @marta-lokhova

**Comment by MonsieurNicolas** [comment]
r+ 599bfd2d7f9361dc7c30f195d870965d528797c1

**Comment by MonsieurNicolas** [comment]
travis infra failure...

**Comment by MonsieurNicolas** [comment]
@latobarita: retry

**Pull request merged**
