### PR TITLE
Expand round leaders over time

### PR DESCRIPTION
**Pull request by MonsieurNicolas**
# Description

This PR addresses a couple problems in SCP's nomination protocol:
* defines round leaders not just as the high priority neighbors for the current round, but instead as the union of the high priority neighbors up to that round as described in SCP's internet draft https://tools.ietf.org/html/draft-mazieres-dinrg-scp-05#section-3.4 specifically
     > A node continues to echo votes from the highest priority neighbor in prior rounds as well as the
   current round.
* small bug in equality when comparing weights

# Observed effect in tests

The improvement increases the chances of nodes nominating something as rounds progresses with by about 2x as seen in the following comparison (numbers are percentages the node votes in various configurations).

## master
```
stellar-core test "nomination weight stats"
2019-02-26T16:46:02.549 <test> [default INFO] Testing stellar-core msvc custom
2019-02-26T16:46:02.551 <test> [default INFO] Logging to stellar0.log
2019-02-26T16:46:02.569 <test> [SCP INFO] LocalNode::LocalNode@GAOBN qSet: 2cc575
2019-02-26T16:46:04.593 <test> [SCP INFO] Got 16.4
2019-02-26T16:46:04.594 <test> [SCP INFO] Got 37.9 LOCAL
2019-02-26T16:46:04.600 <test> [SCP INFO] Got 15.66
2019-02-26T16:46:04.612 <test> [SCP INFO] Got 15.24
2019-02-26T16:46:04.633 <test> [SCP INFO] Got 14.8
2019-02-26T16:46:04.656 <test> [SCP INFO] LocalNode::LocalNode@GAOBN qSet: 172dcb
2019-02-26T16:46:06.012 <test> [SCP INFO] Got 57.88 LOCAL
2019-02-26T16:46:06.013 <test> [SCP INFO] Got 21.12
2019-02-26T16:46:06.031 <test> [SCP INFO] Got 21
2019-02-26T16:46:06.063 <test> [SCP INFO] LocalNode::LocalNode@GAOBN qSet: c85b05
2019-02-26T16:46:09.319 <test> [SCP INFO] Got 14.88 OUTER
2019-02-26T16:46:09.320 <test> [SCP INFO] Got 32.34 LOCAL
2019-02-26T16:46:09.325 <test> [SCP INFO] Got 14.08 OUTER
2019-02-26T16:46:09.326 <test> [SCP INFO] Got 8.84 INNER
2019-02-26T16:46:09.347 <test> [SCP INFO] Got 13.52 OUTER
2019-02-26T16:46:09.376 <test> [SCP INFO] Got 8.6 INNER
2019-02-26T16:46:09.380 <test> [SCP INFO] Got 7.74 INNER
===============================================================================
All tests passed (3000 assertions in 1 test case)
```

## this PR
```
stellar-core test "nomination weight stats"
2019-02-26T16:43:29.890 <test> [default INFO] Testing stellar-core msvc custom
2019-02-26T16:43:29.891 <test> [default INFO] Logging to stellar0.log
2019-02-26T16:43:29.912 <test> [SCP INFO] LocalNode::LocalNode@GAOBN qSet: 2cc575
2019-02-26T16:43:32.023 <test> [SCP INFO] Got 39.96
2019-02-26T16:43:32.024 <test> [SCP INFO] Got 69.74 LOCAL
2019-02-26T16:43:32.033 <test> [SCP INFO] Got 37.72
2019-02-26T16:43:32.039 <test> [SCP INFO] Got 37.4
2019-02-26T16:43:32.041 <test> [SCP INFO] Got 35.9
2019-02-26T16:43:32.061 <test> [SCP INFO] LocalNode::LocalNode@GAOBN qSet: 172dcb
2019-02-26T16:43:33.517 <test> [SCP INFO] Got 85.34 LOCAL
2019-02-26T16:43:33.518 <test> [SCP INFO] Got 47.66
2019-02-26T16:43:33.526 <test> [SCP INFO] Got 48.12
2019-02-26T16:43:33.547 <test> [SCP INFO] LocalNode::LocalNode@GAOBN qSet: c85b05
2019-02-26T16:43:36.936 <test> [SCP INFO] Got 36.84 OUTER
2019-02-26T16:43:36.937 <test> [SCP INFO] Got 63.56 LOCAL
2019-02-26T16:43:36.962 <test> [SCP INFO] Got 34.54 OUTER
2019-02-26T16:43:36.991 <test> [SCP INFO] Got 23.16 INNER
2019-02-26T16:43:37.018 <test> [SCP INFO] Got 34.04 OUTER
2019-02-26T16:43:37.046 <test> [SCP INFO] Got 22.86 INNER
2019-02-26T16:43:37.080 <test> [SCP INFO] Got 22.46 INNER
===============================================================================
All tests passed (3000 assertions in 1 test case)
```

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v5.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [x] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

**Comment by graydon** [comment]
I read it over and this looks ok to me but it needs another pair of eyes. @jonjove ?

**Comment by jonjove** [comment]
r+ ce9eeb9

**Comment by MonsieurNicolas** [comment]
@latobarita: retry

**Comment by MonsieurNicolas** [comment]
not sure what the failure was: test should not fail (passes on my machine)

**Comment by graydon** [comment]
r+ 7a171e7

**Pull request merged**
