### PR TITLE
Create passive offers during fuzzer setup

### PR DESCRIPTION
**Pull request by rokopt**
# Create passive offers during fuzzer setup

Part of #1376 

Create a couple of passive offers during fuzzer setup.

We will probably look for many other interesting combinations of offers to add in the future, but I figured I'd start simple and try to validate an approach.

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v5.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [ ] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
It seems to me that we're continuing to move forward with highly symmetrical setup - 0 spread seems to be quite special for an order book that maybe we should only have that for one pair?

**Comment by rokopt** [comment]
> It seems to me that we're continuing to move forward with highly symmetrical setup - 0 spread seems to be quite special for an order book that maybe we should only have that for one pair?

I think that the ability to create orders with a 0 spread is what's distinct about a passive offer -- that's why I'm creating this new one with a 0 spread.  But maybe I'm misunderstanding that.

Agreed that we should change the spreads in the existing orders, but maybe in a separate PR?

**Comment by MonsieurNicolas** [comment]
> I think that the ability to create orders with a 0 spread is what's distinct about a passive offer -- that's why I'm creating this new one with a 0 spread. But maybe I'm misunderstanding that.

This is correct, I am asking if we should have that many 0 spread order books. I don't understand why we need so many of them.

**Comment by rokopt** [comment]
> > I think that the ability to create orders with a 0 spread is what's distinct about a passive offer -- that's why I'm creating this new one with a 0 spread. But maybe I'm misunderstanding that.
> 
> This is correct, I am asking if we should have that many 0 spread order books. I don't understand why we need so many of them.

I don't know of any (good) reason; it's one of the many further enhancements to setup that I think we both agree we should make.  It just wasn't my goal in this specific PR.

**Comment by rokopt** [comment]
Now that PR #2897 has been merged, this should be done in the same style as that PR.  I've done that in PR #2927 , so this one is superseded.

**Pull request closed without merging**
