### PR TITLE
 (signing weight) must be > threshold

### PR DESCRIPTION
**Pull request by codeck**
jed [1:45 PM] 
ok thats right it is:  (signing weight) must be > threshold
jed [1:47 PM] 
make a PR. cause that is wrong :)

### CODE REVIEW

**Comment by thejollyrogers** [comment]
+r

**Comment by thejollyrogers** [comment]
r+

**Comment by MonsieurNicolas** [comment]
Why are you saying this is wrong?
If there is something wrong, we should update both the documentation and test cases

**Comment by jedmccaleb** [comment]
sorry codeck. I was too tired when I was telling you this last night. it should be >= there can't be signers of weight 0

**Pull request closed without merging**
