### PR TITLE
Test quick restart

### PR DESCRIPTION
**Pull request by vogel**
It seems that stellar-core can survive restart/disconnection only if the next connection comes withing 2 ledgers (about 10 seconds).

It is controlled by HerderImpl::sendSCPStateToPeer::nbLedgers constant (it is 1 more than number of missing ledgers).

Tests for: #1332

### CODE REVIEW

**Comment by vogel** [comment]
I think we should also limit number of GET_SCP_STATE request that we allow from one peer to one (just ignore next ones).
If not, this can be a surface for a DOS.

**Comment by MonsieurNicolas** [comment]
mechanism for dealing with this type of DOS is currently to use trusted peers (that can downgraded to regular peers), so I think it's fine.

**Comment by MonsieurNicolas** [comment]
r+ 4edc16f21e21cd2492a75f4c82168cc886a1936c

**Comment by vogel** [comment]
Rebased on current master, so it will compile

**Pull request merged**
