### PR TITLE
Fixed a compilation issue on Mac introduced in commit e48175f

### PR DESCRIPTION
**Pull request by jonjove**

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
r+ c1bf7f6916fd7cb9947f47c0638015cfd144146f

**Comment by vogel** [comment]
Hmm, we need to do something about output on travis.
With most of the settings output log file exceeds the 4MB travis limit.
With others, something tests does not output anything for a long time (about 10 minutes) - and tests fail.

**Comment by jedmccaleb** [comment]
r+ c1bf7f6

**Comment by vogel** [comment]
@latobarita retry

**Comment by MonsieurNicolas** [comment]
r+ c1bf7f6916fd7cb9947f47c0638015cfd144146f

**Comment by vogel** [comment]
@latobarita: retry

**Comment by vogel** [comment]
Merged manually. Bors/lotobarita bot is working in mysterious ways.

**Pull request merged**
