### PR TITLE
Fix windows (VS) compile errors.

### PR DESCRIPTION
**Pull request by raymens**
Changed dumpxdr.cpp to conform to cpp standard instead of POSIX.
Add missing files to visual studio project file.

**Update 1:**
It seems there is some other bug too. ~The folder **stellar-core-test-798f122b4d19f20e** doesn't get created. For some tests, the folders do get created. Maybe related to a bug in the *new* `bool mkpath(const std::string &path)` implementation?~

```
$ ./stellar-core --test -a
2016-11-08T12:08:25.635 <startup> [Fs DEBUG] created dir stellar-core-test-798f122b4d19f20e
2016-11-08T12:08:25.792 <test> [default INFO ] Testing stellar-core unknown-msvc
2016-11-08T12:08:25.793 <test> [default INFO ] Logging to stellar0.log
2016-11-08T12:08:25.826 <test> [Database INFO ] Connecting to: sqlite3://:memory:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
stellar-core.exe is a Catch v1.2.1 host application.
Run with -? for options

-------------------------------------------------------------------------------
skip list
-------------------------------------------------------------------------------
..\..\src\bucket\BucketTests.cpp(88)
...............................................................................

..\..\src\bucket\BucketTests.cpp(88): FAILED:
due to unexpected exception with message:
  error accessing path: stellar-core-test-798f122b4d19f20e/bucket/tmp

===============================================================================
test cases: 1 | 1 failed
assertions: 1 | 1 failed
```

**Update 2:** 
It seems the base test folder does get created (it just gets deleted after the test), but maybe the *bucket* or *bucket/tmp*  does not. My current best guess would be that it's related to #1063.

**Update 3:**
The *stellar-core-test-xxx/**bucket*** folder doesn't get created. When I explicitly add some code to do this, the tests successfully run. The *tmp*  folder in the *bucket* folder does get created, as long as the *bucket* folder exists. Maybe this is because *tmp* is now in *bucket*, but get's accessed earlier than *bucket* get's created?

**Update 4:**
The issue starts in `TmpDirManager`. It runs the following code:
```cpp
TmpDirManager::TmpDirManager(std::string const& root) : mRoot(root)
{
    clean();
    fs::mkpath(root);
}
```
Which calls the `clean()` function. This function tries to check if the folder exists. But this check happens **before** the `bucket` folder is created. The `fs:exists(..)` only returns false when the file is not found, but will throw an error when the path is not found (because `bucket` doesn't exist).

There are a few options I can think of:
- alter `TmpDirManager` to use a separate `fs::existsXXX` that also catches the *path not found*-error
- try to create the path before cleaning it
- alter the existing `fs:exists`, but this might have big consequences for other parts of the core

### CODE REVIEW

**Comment by jedmccaleb** [comment]
Thanks! I've been meaning to fix the windows build but keep getting pulled away. (We are fixing the tmp issue now. )

**Comment by raymens** [comment]
So it seems it doesn't like the cpp standard functions instead of the POSIX ones. Those changes are optional, as it still compiles for Windows without. But maybe it's just a missing header...

**Comment by raymens** [comment]
I guess I have to add some extra defines just like `mywrite` that will use `_write, _open` etc. in the case of Windows, as I can't seem to find the `_write` types in Linux headers.

**Comment by jedmccaleb** [comment]
Doesn't it compile on windows without the leading underscore? so just `write`

**Comment by raymens** [comment]
Only if I add the following preprocessor flag: `_CRT_NONSTDC_NO_DEPRECATE`. (which I just did). 

It compiles on Windows & Linux (Ubuntu) now.

**Pull request merged**
