### PR TITLE
Updates to how nodes decide to trigger the next ledger

### LINKED ISSUE #1489: flaky test: "SCP messages flooding"
The test
```
Flooding
  scp messages flooding
  outer nodes
  tcp
```

seems to timeout randomly in CI (I also observed that on Windows)

### LINKED ISSUE #1652: Nomination time has large standard deviation
While performing various load testing, we noticed that the time between nomination starting and the ballot protocol starting varies between runs and even between nodes even though there is little variance on the consensus time.

It seems that it's caused by each node having their own opinion (offset) on when rounds should start.

### PR DESCRIPTION
**Pull request by MonsieurNicolas**
resolve #1652 , resolve #1489

This PR has a couple changes that should help with nomination timing:
* leader weights were not always computed right during nomination, leading to some rounds with no leader
* we now align to when the ballot protocol starts for deciding when to trigger
   * while this may introduce a small delay between rounds, this implementation should in most cases allow nodes to automatically synchronize to each other (assuming a uniform time for messages to make it to various nodes)

### CODE REVIEW

**Comment by jedmccaleb** [comment]
r+ 4243d5f

**Comment by MonsieurNicolas** [comment]
Some tests were failing with those changes.

Turns out that the changes increased the chances of the "SCP flooding tests" to fail more often, which allowed me to identify some problems and fixes.

Updated PR includes in addition to the nomination changes:
* ability to change the quorum set when running simulations
* SCP flooding test fix
   * there was a race condition that would cause the whitelist of nodes on the network to kick in while trying to inject SCP messages from other nodes
   * fix was to include those other nodes in the quorum (and make sure that they won't cause externalize to be called)
* fixed a potential performance issue when receiving quorum sets (was causing tests to be much slower than they should be, but the change also makes sense in live environment)

**Comment by vogel** [comment]
LGTM. Should we merge that now?

**Comment by MonsieurNicolas** [comment]
@vogel yes, it can be branch is up to date

**Comment by MonsieurNicolas** [comment]
@latobarita: retry

**Comment by MonsieurNicolas** [comment]
kicking again, tests pass on a couple of dev boxes (except with the occasional bind issue caused by #1635 ), so I am not sure why they fail in travis yet.

**Pull request merged**
