### PR TITLE
#912: Add droppeer, bans and unban commands

### PR DESCRIPTION
**Pull request by vogel**

### CODE REVIEW

**Comment by jedmccaleb** [comment]
oh looks like you need to add `BanManager::dropAll(*this);` to `Database::initialize()` since the table isn't made if creating the DB from scratch.

**Comment by vogel** [comment]
This should be taken care of in upgradeToCurrentSchema. I'll look into that.

**Comment by vogel** [comment]
For some tests upgradeToCurrentSchema is not called - there is no call for ApplicationImpl::start
I think upgradeToCurrentSchema call should be added to ApplicationImpl::newDB

**Comment by jedmccaleb** [comment]
"I think upgradeToCurrentSchema call should be added to ApplicationImpl::newDB"  Yeah I think you are right.

**Comment by vogel** [comment]
PR updated

**Pull request merged**
