### PR TITLE
Remove NtpSynchronizationChecker and related classes

### PR DESCRIPTION
**Pull request by marta-lokhova**
Extracted this from the Work PR (#1819), as this change is actually unrelated to that PR, and it *might* fix crashes in command line catchup (#1885). Specifically, I don't think this code is properly synchronized, causing worker thread to race with main.

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
you forgot to remove the deleted files from the visual studio config files

**Comment by marta-lokhova** [comment]
@MonsieurNicolas done

**Comment by Geod24** [comment]
As a casual observer, I was wondering what was the reasoning for removing this?

**Comment by marta-lokhova** [comment]
@Geod24 Mainly because we'd like to change how we check node's synchronization, and possibly make the checks against other nodes (additionally, we found a few synchronization issues in the current code). I opened an issue to track this also #1815

**Pull request merged**
