### PR TITLE
update asio to 1.13.0

### PR DESCRIPTION
**Pull request by MonsieurNicolas**
This PR updates asio to v1.13.0

### CODE REVIEW

**Comment by graydon** [comment]
r+ 4286d01

**Comment by marta-lokhova** [comment]
r+ 4286d01e660f4dc3dec659ecd9230757c8315ca5

**Comment by MonsieurNicolas** [comment]
@latobarita: retry

**Comment by MonsieurNicolas** [comment]
@latobarita: retry

**Comment by MonsieurNicolas** [comment]
@latobarita: retry

**Pull request merged**
