### PR TITLE
Test HAS in publishqueue

### PR DESCRIPTION
**Pull request by marta-lokhova**

### CODE REVIEW

**Comment by graydon** [comment]
r+ 915eae2

**Comment by MonsieurNicolas** [comment]
@latobarita: retry

**Comment by marta-lokhova** [comment]
Travis looks stuck

**Comment by MonsieurNicolas** [comment]
@latobarita: retry

**Comment by MonsieurNicolas** [comment]
r+ 915eae25384855bb6553e76e3a99d7c9390ca3df

**Pull request merged**
