### PR TITLE
Update default testing behavior to actually be pseudo random by default

### PR DESCRIPTION
**Pull request by MonsieurNicolas**
This PR updates Catch to the latest version (which doesn't ignore certain sections as reported by @jonjove )

It also changes the default behavior for random seeds:
* it now uses a single default seed even by default
   * the previous behavior made it impossible to use a command line seed when running into an issue
   * this also allows to always report the seed to use in order to repro issues
* now it uses time by default instead of a mix of seeds
   * this increases the chances that people actually run into issues

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
@graydon updated with your suggestion (well making the seed by default stable for 24 hours)

**Comment by graydon** [comment]
r+ 6692c3a

**Comment by graydon** [comment]
r+ 7469cd2

**Comment by MonsieurNicolas** [comment]
forgot to run clang-format during the last update

**Comment by MonsieurNicolas** [comment]
r+ ba6bca3c7ee957849f927dcd849c20e56cefbb3c

**Pull request merged**
