### PR TITLE
Fix 'timer cancels' test case

### PR DESCRIPTION
**Pull request by jacereda**

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
This change looks backwards: isn't the test case buggy if it expects things to be in the other order? Right now it triggers from oldest to most recent (I think), and this change triggers from most recent to oldest

**Comment by jacereda** [comment]
Doh! You're right. In any case, I think the test case is correct, I would expect callbacks to be executed in the same order they were registered.

**Comment by jacereda** [comment]
Doesn't look like a very robust fix, but with this small change it passes.

**Comment by MonsieurNicolas** [comment]
This doesn't look right: the comparison function has to follow strict weak ordering, so it cannot return "true" when the vales are equal.
I think it would make sense to actually get to the bottom of the issue for a proper fix. The bug is probably somewhere else in the code.

**Comment by jacereda** [comment]
If you want to keep std::priority_queue I guess something like this could be used. Otherwise, a stable sorter would be an option.

**Comment by graydon** [comment]
Continued in #975 (using mostly the final approach here, but with an explicit last-sequence check rather than size())

**Pull request closed without merging**
