### PR TITLE
Small improvements

### PR DESCRIPTION
**Pull request by jonjove**
# Description
Several small improvements.

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v5.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [ ] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
r+ 829f9856e673d4c46000248eca86558a4153fed9

**Comment by MonsieurNicolas** [comment]
@latobarita: retry

**Comment by jonjove** [comment]
r+ 5c3de2f

**Comment by MonsieurNicolas** [comment]
r+ 23d8298e

**Pull request merged**
