### PR TITLE
Move project version into standalone cpp file

### LINKED ISSUE #1362: move version into its own cpp file
Right now making any change to the tree cause a few files to be rebuilt (on systems where we use `make`), which is quite annoying.

1. build the tree
2. make a bogus change: `echo 1 >> docs/readme.md `
3. run `make` again

expected:
only one file should get rebuild, and the app should be relinked.

actual:
6 files get rebuild

### PR DESCRIPTION
**Pull request by evanlimanto**
Fixes #1362.

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
hey can you rebase this PR? there is a merge commit in there for some reason

**Comment by evanlimanto** [comment]
sorry about that — i've rebased it.

**Comment by MonsieurNicolas** [comment]
Cool, thank you.

Can you move `StellarCoreVersion.h` into the `main` folder so that we don't pollute the root directory? I think the only places where we need to update the include are going to be `HistoryArchive.cpp` and `test.cpp`.

Also, we need to update the visual studio project file - I can help with that when this PR is ready

**Comment by evanlimanto** [comment]
done!

**Comment by MonsieurNicolas** [comment]
@latobarita: retry

**Comment by MonsieurNicolas** [comment]
r+ 0fa7583fc19c11b9b3275ccd7c9978eea11ef966

**Comment by MonsieurNicolas** [comment]
Looks like “format” is not happy when run from a clean dist

**Comment by evanlimanto** [comment]
I've moved `main/StellarCoreVersion.cpp` from `make-mks` into `src/Makefile.am`, which should work.

**Comment by MonsieurNicolas** [comment]
thanks for the quick turnaround!

**Comment by MonsieurNicolas** [comment]
r+ 9249afdc8ef15623b0c13a8b6d0a128819400b9c

**Comment by evanlimanto** [comment]
seems like a clang-format error — fixed.

**Comment by MonsieurNicolas** [comment]
r+ abd3c

**Comment by MonsieurNicolas** [comment]
r+ abd3c53

**Comment by evanlimanto** [comment]
weird, rebuilding from scratch on my machine doesn't give me any errors.

**Comment by MonsieurNicolas** [comment]
Just tried (after running `git clean -xdf` from the root folder)

I am seeing this:
```
main/StellarCoreVersion.cpp:1:37: warning: extra tokens at end of #include directive [-Wextra-tokens]
#include "main/StellarCoreVersion.h"\n\nconst std::string STELLAR_CORE_VERSION = "v9.2.0rc2-7-g75ae5850";
...
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
```

I think the most portable/cleaner way might be to create a template file `StellarCoreVersion.cpp.in` file and have the Makefile do something equivalent to `sed -e 's/@@VERSION@@/v9.2.0rc2-7-g75ae5850/' < src/main/StellarCoreVersion.cpp.in > src/main/StellarCoreVersion.cpp`


 `cat src/main/StellarCoreVersion.cpp.in` :
```c++
#include "main/StellarCoreVersion.h"
const std::string STELLAR_CORE_VERSION = "@@VERSION@@";
```

I also forgot that I need to update the Visual Studio project when this gets merged - I'll take care of it

**Comment by MonsieurNicolas** [comment]
I think this works (apply on top of your change)
```
diff --git a/src/Makefile.am b/src/Makefile.am
index f59f3959..ea803d56 100644
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -41,7 +41,7 @@ main/StellarCoreVersion.cpp: always
        @vers=$$(cd "$(srcdir)" \
                && git describe --always --dirty --tags 2>/dev/null \
                || echo "$(PACKAGE) $(VERSION)"); \
-               echo "#include \"main/StellarCoreVersion.h\"\n\nconst std::string STELLAR_CORE_VERSION = \"$$vers\";" > $@~
+               sed -e "s/%%VERSION%%/$$vers/" < main/StellarCoreVersion.cpp.in > $@~
        @if cmp -s $@~ $@; then rm -f $@~; else \
            mv -f $@~ $@ && printf "echo '%s' > $@\n" "$$(cat $@)"; fi

diff --git a/src/main/StellarCoreVersion.cpp.in b/src/main/StellarCoreVersion.cpp.in
new file mode 100644
index 00000000..5ad16cbe
--- /dev/null
+++ b/src/main/StellarCoreVersion.cpp.in
@@ -0,0 +1,4 @@
+#include "main/StellarCoreVersion.h"
+
+const std::string STELLAR_CORE_VERSION = "%%VERSION%%";
+
```

**Comment by evanlimanto** [comment]
Thanks for the suggestions! I've applied the changes.

**Comment by MonsieurNicolas** [comment]
r+ e1e938d18212e8f53e58d69d0f782f9cf69e4354

**Pull request merged**
