### PR TITLE
Time lock protocol upgrade

### LINKED ISSUE #1123: time lock on the protocol upgrade
Right now the network will upgrade as soon as a quorum of nodes are running the new version. It would be smoother if there was also a date before which validators running the new version won't vote to switch to the new version of the protocol. This will give people some time to switch over.

I suggest we add another configuration value that controls when nodes will start voting for the new version. 

PREFERRED_UPGRADE_DATE=<time stamp>

This controls when they start voting for the new version. Of course they can accept the new version earlier if a quorum out there upgrades earlier.

### PR DESCRIPTION
**Pull request by vogel**
Fixes #1123

### CODE REVIEW

**Comment by jedmccaleb** [comment]
looks good. can you add PREFERRED_UPGRADE_DATETIME to the example.cfg also

**Comment by vogel** [comment]
Updated example configuration file

**Comment by jedmccaleb** [comment]
r+ e1086b4

**Comment by vogel** [comment]
Forgotten do to rebase

**Comment by vogel** [comment]
Rebased

**Comment by jedmccaleb** [comment]
r+ 6e81466

**Pull request merged**
