### PR TITLE
Replace lib/cereal folder with a submodule

### PR DESCRIPTION
**Pull request by jonjove**
The fix for #1473 was introduced in https://github.com/USCiLab/cereal/commit/0022152a85958ca76ce4fe7a26dbdde93c692e22. That commit was included in cereal v1.1.0. Instead of update to v1.1.0, which is quite old at this point, I updated to v1.2.2 which is the most recent release. The change log can be found at https://github.com/USCiLab/cereal/releases.

### CODE REVIEW

**Comment by vogel** [comment]
This one should be merged after history issue is resolved and tested with parallel catchup. We need to check if history serialization/deserialization does not change.

Note: add tests for serialization/deserialization with HAS->string and string->HAS.

**Comment by MonsieurNicolas** [comment]
+1 let's add some simple round trip unit test for `has` and let's get this merged soon

**Comment by MonsieurNicolas** [comment]
r+ e4349eaad2bff03d28952f1fd2f9eebc7c3c96ca

**Comment by MonsieurNicolas** [comment]
r+ 2e0db44f01ae18882200ccb946662b746bb89503

**Comment by MonsieurNicolas** [comment]
@latobarita: retry

**Pull request merged**
