### PR TITLE
moved pending_peers_count and authenticated_peers_count under peers

### LINKED ISSUE #1501: move "authenticated_peers_count" and "pending_peers_count" under a "peers" node (info)
Right now the output of info looks like this:
```
{
   "info" : {
      "UNSAFE_QUORUM" : "UNSAFE QUORUM ALLOWED",
      "authenticated_peers_count" : 38,
      "build" : "v9.1.0",
      "ledger" : {
         "age" : 4,
         "baseFee" : 100,
         "baseReserve" : 5000000,
         "closeTime" : 1516304968,
         "hash" : "0da7b82f8f65e2135857c04b59a6b9e5f259bd6a08a0b1deff92994af6edf8c3",
         "num" : 6759064,
         "version" : 9
      },
      "network" : "Test SDF Network ; September 2015",
      "pending_peers_count" : 0,
      "protocol_version" : 9,
      "quorum" : {
         "6759063" : {
            "agree" : 3,
            "disagree" : 0,
            "fail_at" : 2,
            "hash" : "273af2",
            "missing" : 0,
            "phase" : "EXTERNALIZE"
         }
      },
      "state" : "Synced!"
   }
}
```

authenticated and pending peers counts are related and should be grouped to make it easy for people to see what is going on. This can be done by simply adding a new top level node "peers", and move/rename the values to look like this:
```
     "peers" :
      {
           "authenticated_count": 38,
           "pending_count": 0
      }
```

### PR DESCRIPTION
**Pull request by vogel**
Fixes #1501

Signed-off-by: Rafał Malinowski <rafal.przemyslaw.malinowski@gmail.com>

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
r+ fc48c78e21b49e97de21e312d74ffcc44696a7c4

**Comment by MonsieurNicolas** [comment]
@latobarita: retry (#1488)

**Comment by MonsieurNicolas** [comment]
@latobarita: retry

**Comment by MonsieurNicolas** [comment]
#1489

**Comment by vogel** [comment]
@latobarita: retry

**Comment by MonsieurNicolas** [comment]
@latobarita: retry (#1488)

**Pull request merged**
