### PR TITLE
Added code to implement logRotation function

### PR DESCRIPTION
**Pull request by mvaneijk**
I did not manage to rotate the logfile since the log is not reopened when a function like 'logrotate' copies and truncates the logfile. Then I found this '/logrotate' API endpoint, but this wasn't doing anything more then giving false hope for logrotation....
As I found out an implementation was lacking, I gave it a try.

The easylogging++ library was lacking a trigger to do this directly so I created a workaround which triggers the max size log rolling function in the library, since it is not used anyway.

A GET to /logrotate triggers the function to set the logrotate flag which triggers the library function to rotate the log. It increments the logfile (logfile.log.1 ... logfile.log.2  etc) while maintaining logging in logfile.log.

### CODE REVIEW

**Comment by mvaneijk** [comment]
I agree, will update soon

**Comment by mvaneijk** [comment]
I guess it will work, but still untested, when I have more time I will recompile.

**Comment by mvaneijk** [comment]
Compiled and confirmed functionality

**Comment by graydon** [comment]
Ok, I tested this and it works but I'm not sure, on reflection, that it's doing exactly what we want. It's moving the current log file to a same-named logfile with an ever-increasing suffix. I think what we want to do instead is pick a fixed maximum number of logfiles N to retain, and then "shift-down" the logs: move log to log.1, move log.1 to log.2, move log.2 to log.3, ..., and then delete log.N.

What do you think? I don't really have strong opinions about it, it's just that its current behavior doesn't really seem like what I think of when I think "log rotation".

**Comment by graydon** [comment]
On further discussion with Jed, it seems like there's a standard log rotation command in linux like http://www.linuxcommand.org/man_pages/logrotate8.html that manages the renaming, and all we need to do is like close and reopen the logfile in place after logrotate has moved it away.

**Comment by raymens** [comment]
What about Windows?

**Comment by mvaneijk** [comment]
@graydon; I indeed tried the standard logrotation command, but as you mention the file is not opened again after logrotate closes it.
Another 'feature' in the current version is that the counting starts over when the core is restarted. You cannot omit this without using system calls for scanning the directory the executable is in.

As there is a logrotate for win (http://sourceforge.net/projects/logrotatewin/) I can work with functionality that closes the log, renames to log.tmp or something and opens a new log. The tmp file is than handled by logrotate,

**Comment by mvaneijk** [comment]
implementing #311

**Comment by mvaneijk** [comment]
As a solution to my initial question `copytruncate` for logrotate can be used.

**Comment by mvaneijk** [comment]
Maybe the log library has updated functionality? I have no time atm to check it:
https://github.com/easylogging/easyloggingpp/blob/master/doc/RELEASE-NOTES-v9.81

**Comment by vogel** [comment]
Replaced with #1118

**Pull request closed without merging**
