### PR TITLE
Disable tests

### LINKED ISSUE #1850: generate a minimal stellar-core binary
Right now stellar-core's binary contains both the test suite and the main functionality.

Tests embedded in the main binary increase the binary size a lot, and symbols even more (I've seen stellar-core with a 400MB size lately with full symbols enabled!).

We need to either add a configure flag to explicitly enable the "test" command or build a separate "test" binary (so have two targets, but I am not sure when this would really be used).

### PR DESCRIPTION
**Pull request by vogel**
# Description

Resolves #1850

Add --disable-tests option to ./configure script. This makes binary that is about 1/3 smaller than one with tests.

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v5.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [x] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
looks OK to me ; maybe @graydon has an opinion as he is well versed in the autoconf world

Hold on to rebase until we've merged #1906 
I can take care of the Visual Studio project files

**Comment by graydon** [comment]
Oh, this is awesome! I'm sorry I didn't see it earlier, looks like it's bitrotted a little in the meantime.

**Comment by vogel** [comment]
I'll wait with rebasing for #1972, as it contains new test files

**Comment by vogel** [comment]
Rebased on current master

**Comment by MonsieurNicolas** [comment]
@graydon r+ whenever (I don't know if you had anything to say on this)

**Comment by vogel** [comment]
rebased

**Comment by graydon** [comment]
r+ 43bd5ec

**Comment by graydon** [comment]
(thanks!)

**Comment by graydon** [comment]
@latobarita retry

**Comment by graydon** [comment]
@latobarita: retry

**Pull request merged**
