### PR TITLE
Return non zero value instead of throwing an exception on xdr mismatch

### LINKED ISSUE #3658: XDR mismatch between core and env is making it through CI
The xdr version between rs-soroban-env in core and xdr/protocol-next must match up. If not, then core will fail on startup with an xdr mismatch. This error should be caught when github runs the `next` tests, but for some reason this doesn't happen and the mismatched versions make it into master.

### PR DESCRIPTION
**Pull request by sisuresh**
# Description

Resolves #3658 

# Checklist
- [ ] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [ ] Rebased on top of master (no merge commits)
- [ ] Ran `clang-format` v8.0.0 (via `make format` or the Visual Studio extension)
- [ ] Compiles
- [ ] Ran all tests
- [ ] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
This does not seem to make sense to me: if an exception is thrown, we call `std::abort` in the exception handler which should cause the process to SIGABRT and crash (we see `core dumped` in the logs), so this points to a problem where we're somehow causing the process to return 0 in that case - we really never want to ignore failures if the process is crashing.

**Comment by sisuresh** [comment]
You might be, but it's not just the exception case. This PR explicitly returns 1 and it still passed. I can reproduce this locally so I'm trying some things out.

**Comment by MonsieurNicolas** [comment]
Indeed you're right: even before that fix it was already rerunning the test with lldb meaning the result was not 0 (see runpart)

**Comment by sisuresh** [comment]
Here's the issue - selftest-parallel runs stellar-core twice (once in a perl script to create the test partitions and once in bash). In both cases, an exception can be thrown, but will not cause selftest-parallel to terminate. Instead, it's setting the number of tests to 0, and no test partitions are created (this is done in the perl script). I can terminate on one of the exceptions by setting `pipefail` because `ACTUAL_NUM_TESTS` is set by piping stellar-core's output to `awk`.

At the moment, I haven't figured out how to error in the perl script

I tested this locally, and in this PR with an xdr mismatch -https://github.com/stellar/stellar-core/actions/runs/4139641524/jobs/7157449108.

**Comment by MonsieurNicolas** [comment]
Good catch. In general should we also fail if `NUM_TESTS` is 0? That can point to other problems like bad test pattern that is most likely not what people want to do

**Comment by sisuresh** [comment]
> Good catch. In general should we also fail if `NUM_TESTS` is 0? That can point to other problems like bad test pattern that is most likely not what people want to do

I didn't do this initially because you can technically run with a TEST_SPEC that doesn't map to any tests, but thinking about this again, I can't think of a good reason to return success in this case. I added a check to fail when NUM_TESTS==0.

**Comment by MonsieurNicolas** [comment]
r+ 91768a7ee30131ebf50448907112c3bf73476e09

**Pull request merged**
