### PR TITLE
Corrected typos.

### PR DESCRIPTION
**Pull request by syntaxval**

### CODE REVIEW

**Comment by vogel** [comment]
Hi syntaxval, thanks for the PR. Before we can merge it can you agree to the contributor license: https://docs.google.com/forms/d/1g7EF6PERciwn7zfmfke5Sir2n10yddGGSXyZsq98tVY/viewform

**Comment by syntaxval** [comment]
Done.

**Comment by vogel** [comment]
Thanks!

**Comment by vogel** [comment]
r+ a3355fcd57bbea38a8643ee74c606d5041e5bda5

**Comment by vogel** [comment]
@latobarita: retry

**Comment by vogel** [comment]
Tests passed after re-run: https://travis-ci.org/stellar/stellar-core/builds/244851168
Merging manually

**Pull request merged**
