### PR TITLE
Add tx to restore wasm blob to get-settings-upgrade-txs

### PR DESCRIPTION
**Pull request by sisuresh**
# Description

Resolves https://github.com/stellar/stellar-core/issues/4220

Quickstart and docs will need to be updated.

# Checklist
- [ ] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [ ] Rebased on top of master (no merge commits)
- [ ] Ran `clang-format` v8.0.0 (via `make format` or the Visual Studio extension)
- [ ] Compiles
- [ ] Ran all tests
- [ ] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

**Review by dmkozh — COMMENTED** [review]
This is probably sufficient for a while, but when data starts getting actually evicted, we'll need to come up with a better solution

**Comment by dmkozh** [comment]
r+ 6935d82

**Comment by leighmcculloch** [comment]
> Quickstart and docs will need to be updated.

Heads up that the quickstart script that currently uses this command and that needs updating will be a bit gnarly, so you may want to budget time for that as a slightly larger item rather than as a quick update. The code is linked below and is particularly brittle to the addition of new or less transactions. It probably needs updating to handle an arbitrary number of txs, but if I recall correctly that was challenging because the output of this command includes a variety of things: txs, txids, and a key at the end.

Also, to make it extra fun, anything we update here needs to support any stellar-core versions used in any image, or we need to add guards to the build process to distinguish them. We've done the latter before, but it would be good to avoid that if possible.

https://github.com/stellar/quickstart/blob/6cc1a0b9af10f7bef8f849f0b459832fffa60bef/start#L539-L562

**Comment by sisuresh** [comment]
> Also, to make it extra fun, anything we update here needs to support any stellar-core versions used in any image, or we need to add guards to the build process to distinguish them. We've done the latter before, but it would be good to avoid that if possible.

This is unfortunate. Would it be acceptable if we broke compatibility with older core versions for one release, and then in the next release we add a flag for the restore op?

**Comment by sisuresh** [comment]
> Also, to make it extra fun, anything we update here needs to support any stellar-core versions used in any image, or we need to add guards to the build process to distinguish them. We've done the latter before, but it would be good to avoid that if possible.

@leighmcculloch This is unfortunate. Would it be acceptable if we broke compatibility with older core versions for one release, and then in the next release we add a flag for the restore op?

**Comment by leighmcculloch** [comment]
I don't think we can break it. We can add build arguments to quickstart to signal which is in use, we've done that before, it's just additional time to set up.

**Comment by sisuresh** [comment]
We could also add a conditional that just checks the number of lines returned (7 vs 9). If it's 9, we just read more lines (among a few other changes).

**Comment by leighmcculloch** [comment]
👍🏻 and https://github.com/stellar/quickstart/pull/611 looks good. This logic should be temporary and once all images are using that version or newer we can remove it.

**Pull request merged**
