### PR TITLE
Add starting time for each LocalNode

### PR DESCRIPTION
**Pull request by evanlimanto**
Fixes https://github.com/stellar/stellar-core/issues/1500

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
Thanks for tacking a stab at this!

Please take a moment to fill in the form referenced from https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes before proceeding with a pull request

Going to the actual change.

This PR doesn't seem to be complete:
* it doesn't actually add the information to the `info` endpoint
* the change is done in SCP, I would rather see this in a different place, like Application
* use one of the existing functions for manipulating time (see `util/Timer.h` `pointToISOString` for example)

**Comment by evanlimanto** [comment]
Thanks for getting back to me!

Your comments really helped — I've updated my changes to reflect what was requested.

**Comment by MonsieurNicolas** [comment]
thank you, as simple as that :)
LGTM

**Comment by MonsieurNicolas** [comment]
r+ e4c96d1e88f68cdc9d757cf3b014b40be22139ac

**Pull request merged**
