### PR TITLE
Update license year 2019

### PR DESCRIPTION
**Pull request by EvertonMelo**
### Fix license of use, 
update 2019; 
Format ISO 8869-1;
----------------------------------------------------------------------------------------------------------------------
in Memoriam Guto Schiavon 
guto-schiavon_bitcoin
R.I.P pioneer and friend. 

#ripGUTO

# Description

Resolves #X

# Checklist
- [ ] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [ ] Rebased on top of master (no merge commits)
- [ ] Ran `clang-format` v5.0.0 (via `make format` or the Visual Studio extension)
- [ ] Compiles
- [ ] Ran all tests
- [ ] If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
please review and fill the form in the contributing document

**Comment by EvertonMelo** [comment]
humm interessant Mr  @MonsieurNicolas 
"contributing document"
Which ones have you [signed](https://github.com/stellar/stellar-core/commit/2e3691cc9bab164e4248d214f72389cce81ce7df#diff-7116ef0705885343c9e1b2171a06be0e) before?
Would you copy me?

**Comment by MonsieurNicolas** [comment]
This is standard practice for open source projects, if you can't sign the agreement linked in the project for whatever reason we don't merge your changes.

**Comment by MonsieurNicolas** [comment]
sweeping stale pull requests

**Pull request closed without merging**
