### PR TITLE
Bump tracy to v0.10

### PR DESCRIPTION
**Pull request by marta-lokhova**
Bump tracy to v0.10. Most notable update is the UI overhaul, which makes it much faster and smoother (see https://wolf.nereid.pl/posts/how-tracy-faster/ for a bit more info)

### CODE REVIEW

**Comment by graydon** [comment]
Generally I'm happy to track tracy upstream _but_ there is a bit of awkwardness around rust. We also emit tracy events from soroban and so we need a _precisely_ matched version of [tracy-client](https://crates.io/crates/tracy-client) as well as an unfortunate manual regeneration of the patched/forked [tracy-client-sys](https://github.com/stellar/stellar-core/tree/master/lib/tracy-client-sys) crate we use locally due to various silly technical requirements.

I think it should be mostly sufficient to bump [the tracy-client ref in Cargo.toml](https://github.com/stellar/stellar-core/blob/master/src/rust/Cargo.toml#L14) and then do `cargo-install --locked bindgen` and re-run the [tracy-client-sys regenerate.sh script](https://github.com/stellar/stellar-core/blob/master/lib/tracy-client-sys/src/regenerate.sh) but if you want I can handle this part. Depends how much you want to fight with rust stuff.

**Comment by graydon** [comment]
Also depends on an update on the soroban side: https://github.com/stellar/rs-soroban-env/pull/1417

**Comment by graydon** [comment]
Pushed a change on here that illustrates (it's not quite what needs to be here for a final change, as it references a PR git head over in rs-soroban-env, but .. roughly this is the idea!)

**Comment by marta-lokhova** [comment]
thanks for the fixes @graydon! LGTM.

**Comment by marta-lokhova** [comment]
r+ c3b1269e3c2244cddac8cdaecec6e20461c6ca3b

**Pull request merged**
