### PR TITLE
test create/merge/create tx

### LINKED ISSUE #1403: Error messages when doing series of --catchup-at/--catchup-to commands
For pubnet following scenerio is executed:

```./stellar-core --newdb
./stellar-core --catchup-at 10040000
./stellar-core --catchup-at 10050000
./stellar-core --catchup-to 10070000
```

This results in successful catchup, but with some strange messages on output:

```2017-11-20T13:24:14.289 GDOOK [History INFO] Catching up: applying checkpoint 66/313 (21%)
2017-11-20T13:24:14.797 GDOOK [Ledger ERROR] Exception during tx->apply: Could not update data in SQL [LedgerManagerImpl.cpp:944]
2017-11-20T13:24:14.864 GDOOK [Ledger ERROR] Exception during tx->apply: Could not update data in SQL [LedgerManagerImpl.cpp:944]
2017-11-20T13:24:15.103 GDOOK [History INFO] Catching up: applying checkpoint 67/313 (21%)
2017-11-20T13:24:15.920 GDOOK [History INFO] Catching up: applying checkpoint 68/313 (21%)
2017-11-20T13:24:16.738 GDOOK [History INFO] Catching up: applying checkpoint 69/313 (22%)
2017-11-20T13:24:17.196 GDOOK [Ledger ERROR] Exception during tx->apply: Could not update data in SQL [LedgerManagerImpl.cpp:944]
2017-11-20T13:24:17.544 GDOOK [History INFO] Catching up: applying checkpoint 70/313 (22%)
```

It needs investigation.

### PR DESCRIPTION
**Pull request by vogel**
Fixes #1403

Signed-off-by: Rafał Malinowski <rafal.przemyslaw.malinowski@gmail.com>

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
r+ e7e3148ad0a00d4140d843c76c5e7f3087f79be3

**Comment by MonsieurNicolas** [comment]
Missing clang format

**Comment by vogel** [comment]
Reformatted

**Comment by MonsieurNicolas** [comment]
r+ 2b245a1da415b34dcf1efa7cc7a733d9dd9b227f

**Pull request merged**
