### PR TITLE
make lib/util very different from src/util

### PR DESCRIPTION
**Pull request by vogel**
Signed-off-by: Rafał Malinowski <rafal.przemyslaw.malinowski@gmail.com>

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
Good start.

In addition, I think we should move catch.hpp into `util`, there is no reason to have this file handled differently from the rest.
Also, I would rename `util` to something that screams "external code", like `vendor/util` for example.

**Comment by jedmccaleb** [comment]
why don't we just name it "vendor"

**Comment by MonsieurNicolas** [comment]
all of `lib` should be renamed `vendor` at some point, not just the `util` folder

**Comment by MonsieurNicolas** [comment]
also, let's hold on refreshing this PR until we have a "no churn" window open on libraries.

**Comment by MonsieurNicolas** [comment]
no ROI to do this at this point

**Pull request closed without merging**
