### PR TITLE
Scp signed values during nomination

### PR DESCRIPTION
**Pull request by MonsieurNicolas**
# Description

This PR adds support for additional data attached to values during the nomination round, specifically values during nomination now include the validator identity of the validator that introduced the value to the network.

This makes it easier to understand the flow of SCP messages over the network, can be used for auditing purpose in the future (like see if specific validators are not including certain transactions on purpose for example).

This PR also adds extra logging to makes it easier to diagnose problems

### CODE REVIEW

**Comment by marta-lokhova** [comment]
r+ 8ee5418b5418dc617fd6df42ef60681682efe23d

**Comment by MonsieurNicolas** [comment]
forgot to run clang-format on one commit

**Comment by MonsieurNicolas** [comment]
r+ b0aa76706b8dccb0cded4369611202c8bc147cac

**Comment by MonsieurNicolas** [comment]
@latobarita: retry

**Pull request merged**
