### PR TITLE
Rename ledgerstate to ledgertxn

### PR DESCRIPTION
**Pull request by graydon**
# Description

Just a big renaming of `LedgerState` (and things prefixed by that term) to `LedgerTxn`, because it's .. pretty plainly a transaction object! It has `.commit()` and `.rollback()` methods on it!

(this is a PR atop the comment PR #1897, so includes it as a prefix)

# Checklist
- [x] Reviewed the [contributing](https://github.com/stellar/stellar-core/blob/master/CONTRIBUTING.md#submitting-changes) document
- [x] Rebased on top of master (no merge commits)
- [x] Ran `clang-format` v5.0.0 (via `make format` or the Visual Studio extension)
- [x] Compiles
- [x] Ran all tests
- [x] (NA) If change impacts performance, include supporting evidence per the [performance document](https://github.com/stellar/stellar-core/blob/master/performance-eval/performance-eval.md)

### CODE REVIEW

**Comment by jonjove** [comment]
Looks good to me, rebase on top of merged documentation changes and I'll merge this PR.

**Comment by graydon** [comment]
@jonjove updated

**Comment by graydon** [comment]
r+ 8dfcfcf

**Comment by graydon** [comment]
(self-approving since others already approved and I was just resolving merge conflicts)

**Pull request merged**
