### PR TITLE
History system redesign

### PR DESCRIPTION
**Pull request by graydon**
This is a major refactoring / redesign of the history system _implementation_ in stellar-core. It shares the old interface, both code-wise and files-and-protocols wise. It just works different on the inside.

Its goal is comprehensibility and maintainability. Fewer bugs where it gets into states we don't understand. It is a very small net increase in number of lines of code, but the lines it adds are almost all just the noise of class declarations. Each class is much simpler and more uniform. Far easier control flow, easier to understand and get right.

The design strategy is to separate the concurrency-management, work-queueing, work-dependency-tracking, retrying and error propagating that was formerly sprinkled all through the history system's state machines into its own consolidated base class `Work`, along with a new application-wide `WorkManager` that holds a tree of work and advances them.

There's then a new file `HistoryWork.cpp` that holds a pile of `Work` subclasses that override particular `onFoo` events in the lifecycle of a retryable work-node, each implementing the leaf work-nodes (reading and writing files, running get/put processes, applying records to the database) or interior work-sequencing nodes of the catchup and publish tasks.

In the process I eliminated the in-memory publishing queue, using the database queue directly and consulting it every time we decide which buckets to retain vs. purge. I also removed the publish callback since it wasn't used.

Overall functionality should be identical, aside from a little better behavior around retrying and escalation, hopefully fewer dead / wedged / assert-failure states. The only regression I can see at the moment is that the status messages it emits to logging are a little less refined, though there's plenty of room to improve them, it's late and I wanted to get review of this underway.

I'm going to test this a bit more over the next couple days before landing, but I think it's "mostly done" now.

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
overall: really nice job separating responsibilities. As a bonus, I think it may make implementing `shutdown` simpler (when we want to stop processes and stop scheduling new ones).

**Comment by graydon** [comment]
Ok, comments addressed. Will put through some paces on testnet and livenet tomorrow and then propose we land if all goes well. Thanks for the feedback!

**Comment by MonsieurNicolas** [comment]
While I am reviewing the latest changes, can you also clang-format the code as well?

**Comment by graydon** [comment]
Sure.

**Pull request merged**
