### PR TITLE
Simplify ledger entry cmp 2

### PR DESCRIPTION
**Pull request by vogel**
This is version of #1471 that does not contain commit that does not compile on clang.
I've left #1471 so David can look at it, as it is probably issue with xdrpp.

### CODE REVIEW

**Comment by MonsieurNicolas** [comment]
r+ 9bc2b65ac6a28902d202a1304f73e89ba5c2b496

**Comment by vogel** [comment]
Rebased on current master

**Comment by MonsieurNicolas** [comment]
r+ 893bb95068ce362254941b2c80e6e3456351dbf2

**Comment by MonsieurNicolas** [comment]
@latobarita: retry

**Comment by MonsieurNicolas** [comment]
@latobarita: retry

**Pull request merged**
